### ISSUE TITLE
Extended resource types do not work when using camelCase

### ISSUE THREAD

**Issue by lksnmnn** [ntgussoni/blitz-guard#24]
### What is the problem?

I am getting a 403 on the getCurrentUser response, eventhough the ability was granted.
It works when I use kebab-case.

### Steps to Reproduce

1. Add an extended resource type with camelCase (`"currentUser"`)
2. Add an ability to the GuardBuilder (`can("read", "currentUser")`)
3. Add authorisation to the query (`Guard.authorize("read", "currentUser", getCurrentUser)`) 

### Versions

```
macOS Catalina | darwin-x64 | Node: v12.18.0

blitz: 0.29.2 (global)
blitz: 0.29.2 (local)

  Package manager: npm 
  System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 18.50 GB / 64.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
    Yarn: Not Found
    npm: 6.14.10 - ~/.nvm/versions/node/v12.18.0/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: ~2.14 => 2.14.0 
    @prisma/client: ~2.14 => 2.14.0 
    blitz: 0.29.2 => 0.29.2 
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    typescript: 4.1.3 => 4.1.3 
```

### Other

I'll be able to write a failing test case for this later and maybe submit a PR to fix this issue.

**Comment by ntgussoni** [comment]
@lksnmnn  thanks for reporting this! It was indeed a bug, i've pushed a new version https://github.com/ntgussoni/blitz-guard/releases/tag/v0.3.1. 

Let me know if it gives you any more trouble!

**Comment by lksnmnn** [comment]
Works 👍
