### ISSUE TITLE
Provide more info on Authorization error.

### ISSUE THREAD

**Issue by smashboy** [ntgussoni/blitz-guard#49]
### What do you want and why?
Right now `Guard.authorize()` just throws an authorization error without any context what makes it hard to debug (https://github.com/ntgussoni/blitz-guard/issues/18) and it also hurts UX, because we can not provide detailed info to a user.

So for example I can not check if access was rejected, because user email is not verified or user just not allowed to access this api. Right now I have to use `getAbility` query in order to display a correct message for a user.

### Possible implementation(s)

Right now it will just throw a hardcoded `AuthorizationError`. We can extend this error to a custom one with more detailed info. More info about custom blitz errors [here](https://blitzjs.com/docs/error-handling#custom-errors).

```ts
type GaurdAuthErrorProps = {
  ability: string;
  resource: string;
  reason?: string;
};

class GuardAuthorizationError extends AuthorizationError {
  rule;

  constructor({ ability, resource, reason }: GaurdAuthErrorProps) {
    super();
    this.message = reason || "GUARD: UNAUTHORIZED";
    this.rule = { ability, resource };
  }
}
```

**Comment by ntgussoni** [comment]
@smashboy I wrote a response for this when you posted it but for some reason I didnt save it ... who knows.

I had been thinking about what you propose, and was definitely something that I wanted to add. 
You can check the PR, it introduces a small breaking change in `Guard.can` since now instead of just a boolean it's a tuple
`{can: boolean, reason: string}`

The same happens with `getAbility` in case you are using hooks.

`Guard.authorize` will use the reason as the error message for the AuthorizationError.

I'll leave this PR open before merging it in case you have some ideas.

**Comment by smashboy** [comment]
@ntgussoni Can I have one rule that have different reasons? For example:

```ts
if (isSuspended) {
 cannot("manage", "posts").reason("account/suspended");
}

if(!isUserEmailVerified) {
 cannot("manage", "posts").reason("account/is-not-verified");
}
```

**Comment by ntgussoni** [comment]
> @ntgussoni Can I have one rule that has different reasons? For example:
> 
> ```ts
> if (isSuspended) {
>  cannot("manage", "posts").reason("account/suspended");
> }
> 
> if(!isUserEmailVerified) {
>  cannot("manage", "posts").reason("account/is-not-verified");
> }
> ```

Yes, you can have the same rule multiple times under different conditions

**Comment by smashboy** [comment]
@ntgussoni  Also it would be nice to have an access to `query/mutation input` in `ability.ts` to check some data before allowing something. Right  now I can access query/mutation args only in guard function in `can/cannot` methods. Example:

```ts
const checkPostOwner = async (ctx: Ctx, postId?: string) => {
  const authUserId = ctx.session.userId!;
  const post = await db.collection.findFirst({
    where: {
      id: postId,
    },
    select: {
      userId: true,
    },
  });

  return post?.userId === authUserId;
};

const Guard = GuardBuilder<ExtendedResourceTypes, ExtendedAbilityTypes>(
  async (ctx, { can, cannot }, args) => {
    cannot("manage", "all");

    can("read", "user");

    if (ctx.session.$isAuthorized()) {
      can("manage", "user");

      can("read", "posts")
      if (checkPostOwner(ctx, args?.postId)) {
        can("create", "posts")
        can("update", "posts")
      }
    }
  }
);
```

**Comment by ntgussoni** [comment]
You actually have access to the args inside the guard. Take a look at this https://ntgussoni.github.io/blitz-guard/docs/ability-file#can--cannot

**Comment by smashboy** [comment]
Yeah I know that I can access args directly in `can/cannot` methods, but there there is no way to wrap multiple rules in one condition as it is recommended  here https://ntgussoni.github.io/blitz-guard/docs/ability-file/#best-practices

**Comment by ntgussoni** [comment]
> Yeah I know that I can access args directly in `can/cannot` methods, but there there is no way to wrap multiple rules in one condition as it is recommended  here https://ntgussoni.github.io/blitz-guard/docs/ability-file/#best-practices

> Well tbh it's possible. 
However you gotta be extra careful since the ability file is evaluated on each authorize or can check whereas the guard only runs if the rule matches the one in the authorize function. 

Let me think more about it, in the meantime if you need the args the guard is your friend

**Comment by smashboy** [comment]
OK, thanks for helping figure this out. I have no more questions, so I'm going to close this issue.👍
